name: 'Reusable Workflow'
on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    

jobs:
    resuable_workflow_job:
        runs-on: ubuntu-latest
        steps:
          - uses: ./my_composite@v3
            with:
              configuration-path: ${{ inputs.config-path }}